#Creator: Emerson Sirk (emerson.a.sirk@nasa.gov)

#Last Edited: 1/14/22

from copy_l2file import create_copy
import argparse

#User select through argparse
parser = argparse.ArgumentParser(description='''
#This program takes an input l2 file with geophysical data and creates an 
#output L2 file with the same global attributes and groups as the input. 
#The geophysical data is replaced by the product data generated by a MDN neural network.
''')

ifile = parser.add_argument('--ifile', type=str, required=True)
ofile = parser.add_argument('--ofile', type=str, required=True)
products = parser.add_argument('--products', type=str, default='chl,tss,cdom,pc')

options = parser.parse_args()

#if __name__ == '__main__' :

#call function with user inputs
create_copy(options.ifile, options.ofile, options.products)
