#! /usr/bin/bash -x

# T=test, V=operational
#export tag_type=T
#export BASE_T_TAG="T2024.23"
#export THETAG="T2023.26"
#export THEMESSAGE="
#- fixed OCI rayleigh files, no longer symlinks
#"

export TAGDIR=~/tagdir

if [ ! -f $TAGDIR/tag_comment ]; then
    echo "Comment file not found!"
    exit 1
fi
source $TAGDIR/tag_comment

#-----------------------------------------------------------
# nothing to edit below here
#
export OCSSWROOT=$TAGDIR/ocssw
source $OCSSWROOT/OCSSW_bash.env

if [[ $tag_type = "V" ]]
then
    export BRANCH_OCSSW=$BASE_T_TAG
    export BRANCH_OEL_UTIL=$BASE_T_TAG
    export BRANCH_OEL_HDF4=$BASE_T_TAG
    export BRANCH_VIIRS_L1=$BASE_T_TAG
    export BRANCH_FOCS=$BASE_T_TAG
    export BRANCH_POLARIMETRY=$BASE_T_TAG
    export BRANCH_UAA=$BASE_T_TAG
else
    export BRANCH_OCSSW=develop
    export BRANCH_OEL_UTIL=develop
    export BRANCH_OEL_HDF4=develop
    export BRANCH_VIIRS_L1=develop
    export BRANCH_FOCS=develop
    export BRANCH_POLARIMETRY=develop
    export BRANCH_UAA=develop
fi

#
# nice function to check the return value
#
check_return () {
    if [[ $? -ne 0 ]]
    then
        echo "-E- $1"
        exit 1
    fi
}

#
# Checkout the correct branches for repos and submodules
#
cd $TAGDIR/ocssw
check_return "ocssw dir does not exist"
git fetch && git checkout $BRANCH_OCSSW && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "ocssw checkout is bad"
cd oel_util && git fetch && git checkout $BRANCH_OEL_UTIL && if [[ $tag_type != "V" ]]; then git pull; fi && cd ..
check_return "ocssw/oel_util checkout is bad"
cd oel_hdf4 && git fetch && git checkout $BRANCH_OEL_HDF4 && if [[ $tag_type != "V" ]]; then git pull; fi && cd ..
check_return "ocssw/oel_hdf4 checkout is bad"

cd $TAGDIR/viirs_l1
check_return "viirs_l1 dir does not exist"
git fetch && git checkout $BRANCH_VIIRS_L1 && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "viirs_l1 checkout is bad"
cd oel_util && git fetch && git checkout $BRANCH_OEL_UTIL && if [[ $tag_type != "V" ]]; then git pull; fi && cd ..
check_return "viirs_l1/oel_util checkout is bad"

cd $TAGDIR/focs
check_return "focs dir does not exist"
git fetch && git checkout $BRANCH_FOCS && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "focs checkout is bad"
cd oel_util && git fetch && git checkout $BRANCH_OEL_UTIL && if [[ $tag_type != "V" ]]; then git pull; fi && cd ..
check_return "focs/oel_util checkout is bad"
cd oel_hdf4 && git fetch && git checkout $BRANCH_OEL_HDF4 && if [[ $tag_type != "V" ]]; then git pull; fi && cd ..
check_return "focs/oel_hdf4 checkout is bad"

cd $TAGDIR/polarimetry/harp
check_return "harp dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "harp checkout is bad"

cd $TAGDIR/polarimetry/pyspex
check_return "pyspex dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "pyspex checkout is bad"

cd $TAGDIR/polarimetry/spex
check_return "spex dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "spex checkout is bad"

cd $TAGDIR/polarimetry/fastmapol
check_return "polarimetry fastmapol dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "fastmapol checkout is bad"

cd $TAGDIR/polarimetry/remotap
check_return "polarimetry remotap dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "remotap checkout is bad"

cd $TAGDIR/polarimetry/gpc
check_return "GPC dir does not exist"
git fetch && git checkout $BRANCH_POLARIMETRY && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "GPC checkout is bad"

cd $TAGDIR/sat/unified_dtdb_aerosol
check_return "UAA dir does not exist"
git fetch && git checkout $BRANCH_UAA && if [[ $tag_type != "V" ]]; then git pull; fi
check_return "UAA checkout is bad"

#
# make sure all root repos are checked in and clean
#
cd $TAGDIR/ocssw
git status | grep "nothing to commit, working tree clean"
check_return "ocssw is not clean"

cd $TAGDIR/viirs_l1
git status | grep "nothing to commit, working tree clean"
check_return "viirs_l1 is not clean"

cd $TAGDIR/focs
git status | grep "nothing to commit, working tree clean"
check_return "focs is not clean"

#
# build viirs_l1
#
cd $TAGDIR/viirs_l1
rm -rf build
mkdir build
cd build
cmake ..
check_return "viirs_l1 cmake failed"
make -j 20 install
check_return "viirs_l1 make failed"

#
# build focs
#
cd $TAGDIR/focs
rm -rf build
mkdir build
cd build
cmake ..
check_return "focs cmake failed"
make -j 20 install
check_return "focs make failed"

#
# build ocssw
#
cd $TAGDIR/ocssw
rm -rf build
mkdir build
cd build
cmake .. -DBUILD_ALL=1
check_return "ocsssw cmake failed"
make -j 20 install
check_return "ocssw make failed"

#
# build harp
#
cd $TAGDIR/polarimetry/harp/hipp
rm -rf build
mkdir build
cd build
cmake ..
check_return "harp hipp cmake failed"
# somehow a parallel make does not quite work (deleted -j 20)
make install
check_return "harp hipp make failed"

#
# build GPC
#
cd $TAGDIR/polarimetry/gpc
rm -rf build
mkdir build
cd build
cmake ..
check_return "GPC cmake failed"
make -j 20 install
check_return "GPC make failed"

#
# build UAA
#
cd $TAGDIR/sat/unified_dtdb_aerosol
rm -rf build
mkdir build
cd build
cmake ..
check_return "UAA cmake failed"
# somehow a parallel make does not quite work (deleted -j 20)
make install
check_return "UAA make failed"


#
# make the ocssw/scripts PEX files
#



#
# make the polarimetry PEX files
#



#
# make the tag in git
#
cd $TAGDIR/ocssw &&           git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "ocssw tag failed"
cd $TAGDIR/ocssw/oel_util &&  git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "oel_util tag failed"
cd $TAGDIR/ocssw/oel_hdf4 &&  git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "oel_hdf4 tag failed"
cd $TAGDIR/viirs_l1 &&        git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "viirs_l1 tag failed"
cd $TAGDIR/focs &&            git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "focs tag failed"

cd $TAGDIR/polarimetry/harp &&      git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "harp tag failed"
cd $TAGDIR/polarimetry/pyspex &&    git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "pyspex tag failed"
cd $TAGDIR/polarimetry/spex &&      git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "spex tag failed"
cd $TAGDIR/polarimetry/fastmapol && git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "polarimetry/fastmapol tag failed"
cd $TAGDIR/polarimetry/remotap &&   git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "polarimetry/remotap tag failed"
cd $TAGDIR/polarimetry/gpc &&       git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "polarimetry/gpc tag failed"

cd $TAGDIR/sat/unified_dtdb_aerosol && git tag $THETAG -a -m "$THEMESSAGE" && git push --tags
check_return "UAA tag failed"

# build the tag for all archetecures
# make sure build is clean
cd
build_manifest_ocssw -t $THETAG
check_return "build_manifest_ocssw failed"

#
# transfer the new code to the manifest directory
# check what files are actually copied
#

cd ~/ocssw-manifest
update_manifest_dirs --live
manifest_ocssw status

echo
read -p "Do you want to continue (y/n) " answer
if [[ $answer != "y" ]]
then
    echo "Exiting..."
    exit 1
fi

#
# create the tag
#
cd ~/ocssw-manifest
manifest_ocssw push $THETAG

